# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-30 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixx', '0003_remove_user_isloggedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('n', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
