# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-30 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flixx', '0005_genre_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='a',
        ),
    ]
