# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flixx', '0007_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField()),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flixx.movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flixx.user')),
            ],
        ),
    ]
