# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-01 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flixx', '0008_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='like',
        ),
    ]
